//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 02:01:24 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cs548.stevens.edu/clinic/service/web/rest/data/dap")
package edu.stevens.cs548.clinic.service.web.rest.data.dap;
