//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.12 at 11:20:45 AM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cs548.stevens.edu/clinic/service/web/data/provider", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.stevens.cs548.clinic.service.dto.provider;
